helm:
  chart: "./"
targetCustomizations:
- name: ring0
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      group: ring0
- name: ring1
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      group: ring1
